[package]
name = "solution-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.111", features = ["full"] }
quote = "1.0.42"
inventory = "0.3.21"
proc-macro2 = "1.0.103"
